version: 2.1
jobs:
  build:
    working_directory: ~/js-mocha-chai-graphql
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@8"
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test
